name: Node CI

on:
  push:
    branches:
    - develop
    - xen/redwood.master
  pull_request:
    branches:
    - '**'

jobs:    
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: 20.8.1

    - name: Set up .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Test
      run: npm run test --testPathIgnorePatterns=".*/__fixtures__/.*|/src/course-home|src/course-home|src/course-home/|src/courseware/CoursewareContainer.test.jsx"

    - name: i18n Extract
      run: npm run i18n_extract
    
    - name: Build
      run: npm run build
    
